// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbIjHQp1jA6X916ybO9WX94_VyzSu9pmg',
    appId: '1:1078843075023:web:f3324b633b3c4d5b200aba',
    messagingSenderId: '1078843075023',
    projectId: 'informatik-projekt-6e4f5',
    authDomain: 'informatik-projekt-6e4f5.firebaseapp.com',
    databaseURL: 'https://informatik-projekt-6e4f5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'informatik-projekt-6e4f5.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlCgRwCCcNDs1pXRC3-e2yAp91mabh0cg',
    appId: '1:1078843075023:android:ecd8d2afc9ce0cdd200aba',
    messagingSenderId: '1078843075023',
    projectId: 'informatik-projekt-6e4f5',
    databaseURL: 'https://informatik-projekt-6e4f5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'informatik-projekt-6e4f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1SKP5iSNjlVnGdi-Wd3FRKyfPAg97Mqg',
    appId: '1:1078843075023:ios:71dfaa96bde868c0200aba',
    messagingSenderId: '1078843075023',
    projectId: 'informatik-projekt-6e4f5',
    databaseURL: 'https://informatik-projekt-6e4f5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'informatik-projekt-6e4f5.appspot.com',
    androidClientId: '1078843075023-7sa9ua2r346hu8qbt19phbj53rqruogg.apps.googleusercontent.com',
    iosClientId: '1078843075023-2e0s2rj8lfhlcspplharnugbap162qda.apps.googleusercontent.com',
    iosBundleId: 'com.example.infoProjekt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1SKP5iSNjlVnGdi-Wd3FRKyfPAg97Mqg',
    appId: '1:1078843075023:ios:f62a4125d0df649b200aba',
    messagingSenderId: '1078843075023',
    projectId: 'informatik-projekt-6e4f5',
    databaseURL: 'https://informatik-projekt-6e4f5-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'informatik-projekt-6e4f5.appspot.com',
    androidClientId: '1078843075023-7sa9ua2r346hu8qbt19phbj53rqruogg.apps.googleusercontent.com',
    iosClientId: '1078843075023-f6kul7n54e0s04thdn732045pfdcn31a.apps.googleusercontent.com',
    iosBundleId: 'com.example.infoProjekt.RunnerTests',
  );
}
